package crud;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Form_Tugas extends javax.swing.JFrame {

    private DefaultTableModel tabmode;
    private ResultSet hasil;
    private CRUD aa; 

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_Tugas.class.getName());

    /**
     * Creates new form Form_Tugas
     */
    public Form_Tugas() throws SQLException {
    initComponents();
    aa = new CRUD(); // panggil class CRUD
    tampil_database();
    tampil_statistik();
}
    public void tampil_database() {
    Object[] kolom = {"ID", "Mata Kuliah", "Deskripsi", "Deadline"};
    tabmode = new DefaultTableModel(null, kolom);
    tabel_tugas.setModel(tabmode);
    tabel_tugas.setAutoCreateRowSorter(true);


    try {
        hasil = aa.tampilData();
        while (hasil.next()) {
            aa.setID(hasil.getString("id_tugas"));
            aa.setMatkul(hasil.getString("mata_kuliah"));
            aa.setDeskripsi(hasil.getString("deskripsi"));
            aa.setDeadline(hasil.getString("deadline"));

            String[] data = {aa.getID(), aa.getMatkul(), aa.getDeskripsi(), aa.getDeadline()};
            tabmode.addRow(data);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data: " + e.getMessage());
    }
}
    public void tampil_statistik() {
    try {
        Connection con = KoneksiMysql.koneksiDB();
        Statement st = con.createStatement();

        // Jumlah tugas
        ResultSet rs1 = st.executeQuery("SELECT COUNT(*) FROM tugas");
        if (rs1.next()) {
            lbl_jumlah_tugas.setText("Jumlah Tugas: " + rs1.getInt(1));
        }

        // Jumlah matkul unik
        ResultSet rs2 = st.executeQuery("SELECT COUNT(DISTINCT mata_kuliah) FROM tugas");
        if (rs2.next()) {
            lbl_jumlah_matkul.setText("Jumlah Matkul: " + rs2.getInt(1));
        }

        // Deadline terdekat
        ResultSet rs3 = st.executeQuery("SELECT deadline FROM tugas WHERE deadline >= CURDATE() ORDER BY deadline ASC LIMIT 1");
        if (rs3.next()) {
            lbl_deadline_terdekat.setText("Deadline Terdekat: " + rs3.getString(1));
        } else {
            lbl_deadline_terdekat.setText("Deadline Terdekat: -");
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

   public void reset_text() {
        txt_id.setText("");
        txt_matkul.setText("");
        txt_deskripsi.setText("");
        date_deadline.setDate(null);
    }
   
   private boolean validasiInput() {
    String id = txt_id.getText().trim();
    String matkul = txt_matkul.getText().trim();
    String deskripsi = txt_deskripsi.getText().trim();
    Date deadline = date_deadline.getDate();

    if (id.isEmpty() || matkul.isEmpty() || deskripsi.isEmpty() || deadline == null) {
        JOptionPane.showMessageDialog(this, "Semua field wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return false;
    }

    if (!id.matches("[a-zA-Z0-9]+") || id.length() > 10) {
        JOptionPane.showMessageDialog(this, "ID hanya boleh huruf/angka (maks. 10 karakter)");
        return false;
    }

    if (matkul.length() > 50) {
        JOptionPane.showMessageDialog(this, "Nama mata kuliah terlalu panjang (maks. 50 karakter)");
        return false;
    }

    return true;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        date_deadline = new com.toedter.calendar.JDateChooser();
        txt_matkul = new javax.swing.JTextField();
        txt_deskripsi = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_tugas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        lbl_jumlah_tugas = new javax.swing.JLabel();
        lbl_jumlah_matkul = new javax.swing.JLabel();
        lbl_deadline_terdekat = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setText("ID                 :");

        jLabel2.setText("Mata Kuliah   :");

        jLabel3.setText("Deskripsi      :");

        jLabel4.setText("Deadline       :");

        txt_matkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matkulActionPerformed(evt);
            }
        });

        txt_deskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deskripsiActionPerformed(evt);
            }
        });

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        tabel_tugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_tugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_tugasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_tugas);

        jLabel5.setText("Cari Mata Kuliah");

        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        lbl_jumlah_tugas.setText("Jumlah Tugas");

        lbl_jumlah_matkul.setText("Jumlah Matkul");

        lbl_deadline_terdekat.setText("Deadline Terdekat");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("✏️  FORM DATA TUGAS KULIAH");

        jLabel7.setText("📊 Statistik:");

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btn_simpan)
                        .addGap(21, 21, 21)
                        .addComponent(btn_ubah)
                        .addGap(15, 15, 15)
                        .addComponent(btn_hapus)
                        .addGap(18, 18, 18)
                        .addComponent(btn_reset)
                        .addGap(21, 21, 21)
                        .addComponent(btn_keluar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(date_deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lbl_jumlah_tugas)
                            .addComponent(lbl_jumlah_matkul)
                            .addComponent(lbl_deadline_terdekat)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_id))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txt_deskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cari, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(btn_cari)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_deskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(date_deadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_hapus)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_reset)
                        .addComponent(btn_keluar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_simpan)
                            .addComponent(btn_ubah))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(lbl_jumlah_tugas)
                        .addGap(6, 6, 6)
                        .addComponent(lbl_jumlah_matkul)
                        .addGap(6, 6, 6)
                        .addComponent(lbl_deadline_terdekat))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
            if (!validasiInput()) return;
            try {
                String deadline = new SimpleDateFormat("yyyy-MM-dd").format(date_deadline.getDate());
                aa.setID(txt_id.getText());
                aa.setMatkul(txt_matkul.getText());
                aa.setDeskripsi(txt_deskripsi.getText());
                aa.setDeadline(deadline);
                aa.simpanData();
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
                tampil_database();
                reset_text();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal simpan: " + e.getMessage());
            } 
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        if (!validasiInput()) return;
        try {
            String deadline = new SimpleDateFormat("yyyy-MM-dd").format(date_deadline.getDate());
            aa.setID(txt_id.getText());
            aa.setMatkul(txt_matkul.getText());
            aa.setDeskripsi(txt_deskripsi.getText());
            aa.setDeadline(deadline);
            aa.ubahData();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah");
            tampil_database();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ubah: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
      if (txt_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus");
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Yakin hapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    aa.setID(txt_id.getText());
                    aa.hapusData();
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                    tampil_database();
                    reset_text();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Gagal hapus: " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset_text();

    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
       int keluar = JOptionPane.showConfirmDialog(this, "Yakin keluar aplikasi?", "Keluar", JOptionPane.YES_NO_OPTION);
        if (keluar == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void tabel_tugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_tugasMouseClicked
      int baris = tabel_tugas.rowAtPoint(evt.getPoint());
        txt_id.setText(tabel_tugas.getValueAt(baris, 0).toString());
        txt_matkul.setText(tabel_tugas.getValueAt(baris, 1).toString());
        txt_deskripsi.setText(tabel_tugas.getValueAt(baris, 2).toString());

        try {
            Date tgl = new SimpleDateFormat("yyyy-MM-dd").parse(tabel_tugas.getValueAt(baris, 3).toString());
            date_deadline.setDate(tgl);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tabel_tugasMouseClicked

    private void txt_deskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deskripsiActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        String keyword = txt_cari.getText().trim();
    if (keyword.isEmpty()) {
        tampil_database(); // tampilkan semua
        return;
    }

    Object[] kolom = {"ID", "Mata Kuliah", "Deskripsi", "Deadline"};
    tabmode = new DefaultTableModel(null, kolom);
    tabel_tugas.setModel(tabmode);

    try {
        String sql = "SELECT * FROM tugas WHERE mata_kuliah LIKE '%" + keyword + "%'";
        Connection con = KoneksiMysql.koneksiDB();
        Statement st = con.createStatement();
        ResultSet hasil = st.executeQuery(sql);

        while (hasil.next()) {
            String[] data = {
                hasil.getString("id_tugas"),
                hasil.getString("mata_kuliah"),
                hasil.getString("deskripsi"),
                hasil.getString("deadline")
            };
            tabmode.addRow(data);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mencari data: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        btn_cariActionPerformed(evt); // otomatis klik tombol cari saat tekan enter
    }//GEN-LAST:event_txt_cariActionPerformed

    private void txt_matkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matkulActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private com.toedter.calendar.JDateChooser date_deadline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_deadline_terdekat;
    private javax.swing.JLabel lbl_jumlah_matkul;
    private javax.swing.JLabel lbl_jumlah_tugas;
    private javax.swing.JTable tabel_tugas;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_deskripsi;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_matkul;
    // End of variables declaration//GEN-END:variables
    }
